# Generated by Django 4.2.5 on 2023-11-25 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("search_term", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("url", models.TextField()),
                ("total_review_count", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0)),
                ("price", models.FloatField(default=0)),
                ("website", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
