# Generated by Django 4.2.7 on 2023-11-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="total_review_count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
